# Copyright (c) 2022 jovami. All Rights Reserved.

image: maven:3.8.6-eclipse-temurin-19-alpine

pipelines:
  default:
    - parallel:
      - step:
          name: Build and Test
          caches:
            - maven
          script:
            - mvn -B verify --file pom.xml
# image: scottieg40/linux:buildEnv

# pipelines:
#   default:
#       - step:
#           name: build main
#           script:
#               - apt-get update && apt-get install -y git
#               - git submodule update --recursive --init
#               - make cclean c
#               - make cclean ctest
