# Copyright (c) 2022 jovami. All Rights Reserved.

image: scottieg40/linux:buildEnv

pipelines:
  default:
      - step:
          name: build main
          script:
              - apt-get update && apt-get install -y git
              - git submodule update --recursive --init
              - make cclean c
              - make cclean ctest
